### ISSUE TITLE
Typo in conf.yml

### ISSUE THREAD

**Issue by joelthe1** [isi-nlp/rtg#9]
## Bug Report
One of the valid keys in the `conf.yml` is `suit` (e.g. [here](https://github.com/isi-nlp/rtg/blob/master/examples/transformer.base.yml#L58)). I believe this is a typo.

## Resolution
This key should be renamed to `suite` as described in the [docs](https://isi-nlp.github.io/rtg/#conf).

**Comment by thammegowda** [comment]
Fixed in 0.5
